cloud:
  aws:
    region:
      static: ue-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIAYF2BSZYZLK22FMNK
      secret-key: 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
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error


