
cloud:
  aws:
    region:
      auto: false
      static:  us-east-1
      use-default-aws-region-chain: true
    stack: false
    stack.auto: false
    credentials:
      access-key: AKIAYF2BSZYZLK22FMNK
      secret-key: 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
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
