
cloud:
  aws:
    region:
      auto: false
      static: us-east-1
      use-default-aws-region-chain: true
    stack: false
    stack.auto: false
    credentials:
      access-key: AKIAYF2BSZYZEJ56SRNM
      secret-key: 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
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
